# Generated by Django 2.1.5 on 2019-02-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatoo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('type', models.CharField(choices=[('Эскиз', 'Готовая работа'), ('Эскиз', 'Готовая работа')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.DeleteModel(
            name='Scetch',
        ),
        migrations.DeleteModel(
            name='Tatoo',
        ),
    ]
