# Generated by Django 2.1.7 on 2019-02-15 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tatoo', '0004_zalupa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zalupa',
        ),
    ]
